# Generated by Django 4.0.2 on 2022-02-13 13:42

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Posts category',
                'verbose_name_plural': 'Posts Categories',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('pic', models.FileField(upload_to='posts_medias', validators=[blog.models.validate_image], verbose_name='picture')),
                ('pic_alter', models.CharField(blank=True, help_text="It's the alt attrbiute of the img (image).", max_length=75, null=True, verbose_name='picture alternative')),
            ],
            options={
                'verbose_name': 'Media for posts',
                'verbose_name_plural': 'Medias for posts',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('body', models.TextField(verbose_name='body')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.media')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
